import Batik1 from "@/assets/img/batik/batik1.jpg";
import Batik2 from "@/assets/img/batik/batik2.jpg";
import Batik3 from "@/assets/img/batik/batik3.jpg";
import Batik4 from "@/assets/img/batik/batik4.png";

export const products = [
  {
    id: 1,
    name: "Batik Tulis Modern",
    image: Batik1,
    price: 500000,
    rating: 4.5,
    gender: "Pria",
    sold: 120,
  },
  {
    id: 2,
    name: "Batik Cap Tradisional",
    image: Batik4,
    price: 350000,
    rating: 4,
    gender: "Wanita",
    sold: 85,
  },
  {
    id: 3,
    name: "Batik Pekalongan",
    image: Batik2,
    price: 450000,
    rating: 5,
    gender: "Unisex",
    sold: 200,
  },
  {
    id: 4,
    name: "Batik Mega Mendung",
    image: Batik3,
    price: 600000,
    rating: 4.8,
    gender: "Pria",
    sold: 95,
  },
  {
    id: 5,
    name: "Batik Kawung",
    image: Batik1,
    price: 400000,
    rating: 4.3,
    gender: "Wanita",
    sold: 75,
  },
  {
    id: 6,
    name: "Batik Parang",
    image: Batik2,
    price: 550000,
    rating: 4.7,
    gender: "Unisex",
    sold: 150,
  },
  {
    id: 7,
    name: "Batik Sekar Jagad",
    image: Batik1,
    price: 650000,
    rating: 5,
    gender: "Pria",
    sold: 110,
  },
  {
    id: 8,
    name: "Batik Lasem",
    image: Batik3,
    price: 300000,
    rating: 3.8,
    gender: "Wanita",
    sold: 60,
  },
  {
    id: 9,
    name: "Batik Cirebon",
    image: Batik2,
    price: 450000,
    rating: 4.6,
    gender: "Unisex",
    sold: 180,
  },
  {
    id: 10,
    name: "Batik Solo",
    image: Batik3,
    price: 500000,
    rating: 4.5,
    gender: "Pria",
    sold: 130,
  },
  {
    id: 11,
    name: "Batik Yogyakarta",
    image: Batik1,
    price: 550000,
    rating: 4.9,
    gender: "Wanita",
    sold: 140,
  },
  {
    id: 12,
    name: "Batik Bali",
    image: Batik2,
    price: 400000,
    rating: 4.4,
    gender: "Unisex",
    sold: 100,
  },
  {
    id: 13,
    name: "Batik Banten",
    image: Batik2,
    price: 650000,
    rating: 4.7,
    gender: "Pria",
    sold: 90,
  },
  {
    id: 14,
    name: "Batik Malang",
    image: Batik3,
    price: 350000,
    rating: 4.2,
    gender: "Wanita",
    sold: 50,
  },
  {
    id: 15,
    name: "Batik Dayak",
    image: Batik1,
    price: 500000,
    rating: 4.8,
    gender: "Unisex",
    sold: 120,
  },
  {
    id: 16,
    name: "Batik Betawi",
    image: Batik3,
    price: 600000,
    rating: 4.8,
    gender: "Unisex",
    sold: 120,
  },
];
