import Batik1 from "@/assets/img/batik/batik1.jpg";
import Batik2 from "@/assets/img/batik/batik2.jpg";
import Batik3 from "@/assets/img/batik/batik3.jpg";

export const products = [
  {
    id: 1,
    name: "Batik Tulis Modern",
    image: Batik1,
    price: "Rp 500.000",
    rating: 4.5,
    gender: "Pria",
  },
  {
    id: 2,
    name: "Batik Cap Tradisional",
    image: Batik2,
    price: "Rp 350.000",
    rating: 4,
    gender: "Wanita",
  },
  {
    id: 3,
    name: "Batik Pekalongan",
    image: Batik3,
    price: "Rp 450.000",
    rating: 5,
    gender: "Unisex",
  },
  {
    id: 4,
    name: "Batik Mega Mendung",
    image: Batik1,
    price: "Rp 600.000",
    rating: 4.8,
    gender: "Pria",
  },
  {
    id: 5,
    name: "Batik Kawung",
    image: Batik2,
    price: "Rp 400.000",
    rating: 4.3,
    gender: "Wanita",
  },
  {
    id: 6,
    name: "Batik Parang",
    image: Batik3,
    price: "Rp 550.000",
    rating: 4.7,
    gender: "Unisex",
  },
  {
    id: 7,
    name: "Batik Sekar Jagad",
    image: Batik1,
    price: "Rp 650.000",
    rating: 5,
    gender: "Pria",
  },
  {
    id: 8,
    name: "Batik Lasem",
    image: Batik2,
    price: "Rp 300.000",
    rating: 3.8,
    gender: "Wanita",
  },
  {
    id: 9,
    name: "Batik Cirebon",
    image: Batik3,
    price: "Rp 450.000",
    rating: 4.6,
    gender: "Unisex",
  },
  {
    id: 10,
    name: "Batik Solo",
    image: Batik1,
    price: "Rp 500.000",
    rating: 4.5,
    gender: "Pria",
  },
  {
    id: 11,
    name: "Batik Yogyakarta",
    image: Batik1,
    price: "Rp 550.000",
    rating: 4.9,
    gender: "Wanita",
  },
  {
    id: 12,
    name: "Batik Bali",
    image: Batik1,
    price: "Rp 400.000",
    rating: 4.4,
    gender: "Unisex",
  },
  {
    id: 13,
    name: "Batik Banten",
    image: Batik1,
    price: "Rp 650.000",
    rating: 4.7,
    gender: "Pria",
  },
  {
    id: 14,
    name: "Batik Malang",
    image: Batik1,
    price: "Rp 350.000",
    rating: 4.2,
    gender: "Wanita",
  },
  {
    id: 15,
    name: "Batik Dayak",
    image: Batik1,
    price: "Rp 500.000",
    rating: 4.8,
    gender: "Unisex",
  },
];
